version: "3.9"


services:
  django_db:
    image: postgres:12.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: core_app
      PGDATA: /postgres_data

    ports:
      - "5433:5432"

  django_web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - django_db
      - redis

  celery-worker:
    build: .
    command: celery -A core worker -l info
    depends_on:
      - django_web

  celery-beat:
    build: .
    command: celery -A core beat -l info
    depends_on:
      - django_web

  redis:
    image: redis
    restart: always
    container_name: 'demo_app_redis'
    command: redis-server
    ports:
      - '6379:6379'

  nginx:
    image: nginx
    ports:
      - 8081:80


volumes:
  postgres_data: