# Generated by Django 3.1.5 on 2021-01-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_fixlogin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixlogin',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
